### ISSUE TITLE
When Moving pieces, limit selection to what is actually movable

### ISSUE THREAD

**Issue by richardmtl** [sellmerfud/fitl#18]
After issue #17    I decided to adjust and move my pieces. Even though I only have Underground VC and a base, I was given more options. Maybe limit it to only what's there, and include an "All" choice"? Though I get it, you're giving me more options to save a step later. Not sure this is the best place for that kind of efficiency, though.

**Comment by sellmerfud** [comment]
I think this works fine the way it is.  The `adjust` command is not used often during play and was intended for use mostly when testing.
