### ISSUE TITLE
Crash with ARVN bot

### ISSUE THREAD

**Issue by GiacomoDR25** [sellmerfud/fitl#23]
>>> ARVN turn <<<
====================================================
Current card  : #87 - Nguyen Chanh Thi (ARVN, VC, NVA, US)
                ARVN -> (Critical, Shaded), US -> (Critical, Unshaded)
On Deck card  : #105 - Rural Pressure (VC, NVA, US, ARVN)
                US -> (Critical, Unshaded), ARVN -> (Critical, Shaded)
Eligible      : ARVN, US
Acted         : none
Passed        : none
Ineligible    : VC, NVA
(bot or ?):

When bot is selected the program crash. Bug?

**Comment by sellmerfud** [comment]
Could you zip up your saved game directory and attach it.  I can then use it to recreate the problem.
It is in the directory ./fitl-1.17/games/<name of your game>  (Assuming you are using version 1.17)
Thanks.

**Comment by GiacomoDR25** [comment]
[JackDR.zip](https://github.com/user-attachments/files/16173751/JackDR.zip)

This is my saved game in the ./fitl-1.17/games/JackDR

Correct, using 1.17.

**Comment by GiacomoDR25** [comment]
[JackDR.zip](https://github.com/user-attachments/files/16173830/JackDR.zip)

./fitl-1.17/games/JackDR

Correct, 1.17

**Comment by sellmerfud** [comment]
Thanks for reporting this.  
If you download and install version 1.18, you can move the directory `fitl-1.17/games/JackDR`  to `fitl-1.18/games/JackDR` and continue playing your game with the fixed version.  (You will need to first create the `fitl-1.18/games`)

**Comment by GiacomoDR25** [comment]
Thanks!
